package sqlite_test

import "context"

// fixtureEmbedder returns pre-generated text-embedding-3-small vectors.
// Generated by scripts/gen-embeddings. Do not edit manually.
type fixtureEmbedder struct{}

func (f *fixtureEmbedder) Embed(_ context.Context, text string) ([]float32, error) {
	vec, ok := fixtureVecs[text]
	if !ok {
		return nil, nil
	}
	return vec, nil
}
