[tools]
go = "1.26.2"
"go:github.com/golangci/golangci-lint/v2/cmd/golangci-lint" = "v2.12.2"
"go:go.uber.org/nilaway/cmd/nilaway" = "v0.0.0-20260318203545-ad240b12fb4c"

[tasks.build]
run = "go build -o bin/hector ./cmd/hector"

[tasks.test]
run = "go test -race ./..."

[tasks.lint]
run = ["golangci-lint run ./...", "nilaway -exclude-errors-in-files=$(go env GOROOT) ./..."]

[tasks.run]
run = "go run ./cmd/hector -- {{args()}}"
