// gen-embeddings generates test fixture embeddings for TC-02.
// Run once: go run ./scripts/gen-embeddings
// Prints Go source for the fixture embedder map.
package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"strings"

	sdkopenai "github.com/openai/openai-go/v3"
	"github.com/openai/openai-go/v3/option"
)

var texts = []string{
	"we use github to host our code",
	"what is our VCS?",
}

func main() {
	key := os.Getenv("OPENAI_API_KEY")
	if key == "" {
		log.Fatal("OPENAI_API_KEY not set")
	}

	client := sdkopenai.NewClient(option.WithAPIKey(key))
	ctx := context.Background()

	fmt.Println("// Generated by scripts/gen-embeddings. Do not edit manually.")
	fmt.Println("var fixtureVecs = map[string][]float32{")

	for _, text := range texts {
		resp, err := client.Embeddings.New(ctx, sdkopenai.EmbeddingNewParams{
			Input: sdkopenai.EmbeddingNewParamsInputUnion{OfString: sdkopenai.String(text)},
			Model: sdkopenai.EmbeddingModel("text-embedding-3-small"),
		})
		if err != nil {
			log.Fatalf("embed %q: %v", text, err)
		}
		if resp == nil || len(resp.Data) == 0 {
			log.Fatalf("embed %q: empty response", text)
		}
		f64 := resp.Data[0].Embedding
		parts := make([]string, len(f64))
		for i, v := range f64 {
			parts[i] = fmt.Sprintf("%v", float32(v))
		}
		fmt.Printf("\t%q: {%s},\n", text, strings.Join(parts, ", "))
	}

	fmt.Println("}")
}
